<!-- DOCTYPE + Intérieur du body, body inclu sauf la partie changeante -->
<!-- 
------------------------------
-  Partie fixe du Template   -
------------------------------ 
                           -->

<!DOCTYPE html>
<html lang="fr">
  <head>
    <meta charset="utf-8">
    <title>Mon site porte-folio</title>
    <meta name="viewport" content="width=device-width">
    <link rel="stylesheet" href="css/fontawesome-all.min.css">
    <!-- <link rel="stylesheet" href="css/font-awesome.min.css"> -->
    <link href="https://fonts.googleapis.com/css?family=IM+Fell+French+Canon|Italiana|Italianno|Open+Sans|Open+Sans+Condensed:300|Ruthie" rel="stylesheet">
    <link href="css/normalize.css" rel="stylesheet">
    <link rel="icon" type="image/x-icon" href="/favicon.ico" /><link rel="shortcut icon" type="image/x-icon" href="/favicon.ico" /> 
    <link href="css/slider.css" rel="stylesheet">
    <link href="css/bookingConfirm.css" rel="stylesheet">
    <link href="css/style.css" rel="stylesheet">
    <link href="css/add_booking.css" rel="stylesheet">
    
    <script src="js/jquery-3.2.1.min.js"></script>
    
    <script src="js/utilities.js"></script>
    <!-- <script src="js/displayBooking.js"></script> -->
  </head>
  
  <body>
    <!-- ------------------------------ Header / Nav ---------------------------- -->
    
    <!-- ---------------------------------- Main -------------------------------- -->
    <main>
      <?php include $template . '.phtml'; ?>
      
      
      <!-- --------------------------- Presentation ----------------------------- --> 
      
      <!-- ----------------------------- Location ------------------------------- -->
      
      <!-- --------------------------- Photos Gallerie -------------------------- -->
      
      <!-- ------------------------------ Actuality ----------------------------- -->
      
      <!-- ------------------------------- Booking ------------------------------ -->
      
      <!-- -------------------------------- Event ------------------------------- -->
      
      <!-- ------------------------------- Fin du Main -------------------------- -->
    </main>
    
    
    <!-- Footer 2 -->
    <footer class="footerBis"> 
      <section class="container footer-foot">
        <small>Site web réalisé par moi, inspiré par d'autre...</small>
        <a href="#">Mentions légales</a> <!-- AUTRE PAGE A FAIRE -->
      </section>
    </footer>
    <!-- ---------------------------- Fin du Footer ----------------------------- -->
      
  <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script> 
  
  </body>
</html>